# Generated by Django 5.0.2 on 2024-02-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_studenttask_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttask',
            name='taskid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studenttask',
            name='use_id',
            field=models.CharField(max_length=50),
        ),
    ]
